version: "3.9"
services:
  api:
    build: .
    container_name: edumentor-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - edumentor-net
  db:
    image: postgres:16
    container_name: edumentor-postgres
    environment:
      POSTGRES_USER: edumentor
      POSTGRES_PASSWORD: edumentorpw
      POSTGRES_DB: edumentor
    ports:
      - "5432:5432"
    volumes:
      - edumentor-pgdata:/var/lib/postgresql/data
    networks:
      - edumentor-net
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: edumentor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - edumentor-net
volumes:
  edumentor-pgdata:
networks:
  edumentor-net:
